# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
      ad_boleta:
        driver:   "%ad_boleta_database_driver%"
        host:     "%ad_boleta_database_host%"
        port:     "%ad_boleta_database_port%"
        dbname:   "%ad_boleta_database_name%"
        user:     "%ad_boleta_database_user%"
        password: "%ad_boleta_database_password%"
        charset:  UTF8

  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        mappings:
            AppBundle:  ~
            ADPerfilBundle: ~
      ad_boleta:
        connection: ad_boleta
        mappings:
          ADBoletaBundle: ~
        naming_strategy: doctrine.orm.naming_strategy.underscore